# Generated by Django 5.2.15 on 2026-06-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
