# Generated by Django 5.2.15 on 2026-07-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
